<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net472</TargetFrameworks>
    <DisableFody>true</DisableFody>
    <TUnitImplicitUsings>false</TUnitImplicitUsings>
    <EnableTUnitSourceGeneration>false</EnableTUnitSourceGeneration>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="Machine.Specifications" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="Verify.XunitV3" />
    <PackageReference Include="TUnit.Core" />
    <ProjectReference Include="..\Scalpel\Scalpel.csproj" />
  </ItemGroup>
</Project>
